config/routes.rb
Rails.application.routes.draw do
  get 'wishlists/new'

  get 'wishlists/show'

  get 'admin/index'

  get 'orders/new'

  get 'sessions/new'

  get 'user/edit'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'index' =>'home#index'
  get 'admin' => 'admin#index'
  get 'about' => 'home#about'
  get 'users' => 'admin#user'
  get 'shop' => 'books#index'
  get 'bookss' => 'admin#book'
  get 'reviews' => 'admin#review'
  get 'wishlist' => 'wishlists#show'
  root 'home#index'
  get 'orders' => 'admin#order'
  resources :genres
  resources :orders
  resources :wishlists
  resources :users
  resources :carts
  resources :line_items
  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
has_many :reviews, dependent: :destroy
has_many :line_items
has_many :orders, through: :line_items
belongs_to :gerne


before_destroy :in_any_cart

def self.search(search)
  where("title LIKE ?", "%#{search}%") 
  where("abstract LIKE ?", "%#{search}%")
end

private 
def in_any_cart
	if line_items.empty?
		true
	else
		errors.add(:base, "Line_Items presence")
		false
	end
end

	

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	
	def add_book (book_id)
		current_item = line_items.find_by(book_id: book_id)
		if current_item 
			current_item.quantity +=1
		else
			current_item = line_items.build(book_id: book_id)
		end
		current_item
	end
	def total_price
		sum=0
		line_items.each do |item|
		sum = sum + item.total
		end
		sum
	end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  belongs_to :cart
  def total
  	book.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Paypal", "Credit card", "Purchase order" ]
	has_many :line_items, dependent: :destroy
	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
		item.cart_id = nil
		line_items << item
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :wishlist
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :books
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id]= user.id
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def logged_in?
		!current_user.nil?		
	end
	def log_out
		session.delete(:user_id)
    	@current_user = nil
	end
	def current_user?(user)
    user == current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/admin/_allbooks.html.erb
<div class="tab-pane fade active in" id="details" >
                <div id="content" class="span10">
            <div class="row-fluid sortable">        
                <div class="box span12">

                    <div class="box-header" data-original-title>
                        <h2><i class="halflings-icon white user"></i><span class="break"></span>All books</h2>
                   
                        <span><%=link_to new_book_path do%> <button type="button" class="btn btn-lg btn-success">ADDBOOK</button><%end%> <span>
                        <div class="box-icon">
                            <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                            <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">
                        <table class="table table-striped table-bordered bootstrap-datatable datatable">
                          <thead>
                              <tr>
                                  <th>ID</th>
                                  <th>Cover</th>
                                  <th>Info</th>
                                  <th>Price</th>
                                  <th>Publish date</th>
                                  <th>Actions</th>
                              </tr>
                          </thead>   
                          <tbody>
                            <%@books=Book.paginate(:page => params[:page], :per_page => 10)%>
                            <%@books.each do |book|%>
                            <tr>
                              <td><%= book.id%></td>
                              <td><%=image_tag book.image_file_name, :class =>"image-small"%></td>
                                <td><%=book.title%></td>
                                <td><%=book.price%></td>
                                <td class="center"><%=book.created_at.strftime("%d/%m/%Y") %></td>
                                <td class="center">
                                    <%= link_to book_path(book) do%>
                                      <span class="btn btn-success">
                                       <i class="fa fa-info"></i></i>
                                    </span>
                                    <% end %> 
                                    <%= link_to edit_book_path(book) do%>
                                      <span class="btn btn-info">
                                       <i class="fa fa-pencil-square-o"></i>
                                    </span>
                                    <% end %> 
                                    <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' } do%>
                                      <span class="btn btn-danger">
                                       <i class="fa fa-trash"></i>
                                    </span>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                          </tbody>
                      </table>
                            <%= will_paginate @books %>
                    </div>
                </div><!--/span-->
            </div><!--/row-->
            </div>
              </div>

app/views/admin/_allgenres.html.erb
<div class="tab-pane fade" id="companyprofile" >
                <div id="content" class="span10">
            <div class="row-fluid sortable">        
                <div class="box span12">

                    <div class="box-header" data-original-title>
                        <h2><i class="halflings-icon white user"></i><span class="break"></span>All genres</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                            <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                        </div>
                    </div>
                    <div class="box-content">
                        <table class="table table-striped table-bordered bootstrap-datatable datatable">
                          <thead>
                              <tr>
                                  <th>ID</th>
                                  <th>Name</th>
                                  <th>Books</th>
                                  <th>Created date</th>
                                  <th>Actions</th>
                              </tr>
                          </thead>   
                          <tbody>
                            <%Genre.all.each do |genre|%>
                            <tr>
                              <td><%= genre.id%></td>
                                <td><%=genre.name%></td>
                                <td><%=Book.where(genre_id: genre.id).count%></td>
                                <td class="center"><%=genre.created_at.strftime("%d/%m/%Y") %></td>
                                <td class="center">
                                    <%= link_to genre_path(genre) do%>
                                      <span class="btn btn-success">
                                       <i class="fa fa-info"></i></i>
                                    </span>
                                    <% end %> 
                                    <%= link_to edit_genre_path(genre) do%>
                                      <span class="btn btn-info">
                                       <i class="fa fa-pencil-square-o"></i>
                                    </span>
                                    <% end %> 
                                    <%= link_to genre, method: :delete, data: { confirm: 'Are you sure?' } do%>
                                      <span class="btn btn-danger">
                                       <i class="fa fa-trash"></i>
                                    </span>
                                    <% end %>
                                    
                                </td>
                            </tr>
                            <% end %>
                          </tbody>
                      </table>            
                    </div>
                </div><!--/span-->
            </div><!--/row-->
            </div>
              </div>

app/views/admin/_dashboard.html.erb
 <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                       <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Dashboard <small>Statistics Overview</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                        </ol>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge"><%=Review.where('created_at >= ?', 1.month.ago).count%></div>
                                        <div>New comment!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-green">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-tasks fa-users fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge"><%=User.where('created_at >= ?', 1.month.ago).count%></div>
                                        <div>New Users!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <%= link_to users_path do%>
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                                <%end%>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-yellow">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-shopping-cart fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge"><%=Order.where('created_at >=?', 1.month.ago).count%></div>
                                        <div>New Orders!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <%=link_to orders_path do%>
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                                <% end %>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-support fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge"><%=Book.where('created_at >=?', 1.month.ago).count%></div>
                                        <div>New books!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <%= link_to bookss_path do=%>
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                                <%end%>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
                        </div>
                    </div>
                </div>
                <!-- /.row -->


                      
                    </div>
                </div>
            </div>
        </div>

app/views/admin/_sidebar.html.erb
<div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        AIRBOOK admin
                    </a>
                </li>
                <li>
                    <%= link_to 'Dashboard', admin_path%>
                </li>
                <li>
                    <%= link_to 'Users', users_path%>
                </li>
                <li>
                    <%= link_to 'Books', bookss_path%>
                </li>
                <li>
                    <%= link_to 'Orders', orders_path%>
                </li>
                <li>
                    <%= link_to 'View page', root_path%>
                </li>
                <li>
                    <%= link_to "Log out", logout_path, method: :delete%>
                </li>
            </ul>
        </div>

app/views/admin/book.html.erb
 <div id="wrapper">
    <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                        <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Books <small>Books Management</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard / <i class="fa fa-book"></i> Books
                            </li>
                        </ol>
                    </div>
                </div>
<div class="category-tab shop-details-tab"><!--category-tab-->
            <div class="col-sm-12">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#details" data-toggle="tab">All books</a></li>
                <li><a href="#companyprofile" data-toggle="tab">All Genres</a></li>
              </ul>
            </div>
            <div class="tab-content">
              <%=render'allbooks'%>
              <%=render'allgenres'%>
            </div>
          </div><!--/category-tab-->
          
            
            </div>
                </div>
            </div>
        </div>
</div>

       <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/admin/index.html.erb
    <div id="wrapper">
       <%= render 'dashboard'%>
    </div>
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/admin/order.html.erb
 <div id="wrapper">
    <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                        <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Orders <small>Order Management</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard / <i class="fa fa-cart-plus"></i> Orders
                            </li>
                        </ol>
                    </div>
                </div>
            <div id="content" class="span10">
            <div class="row-fluid sortable">        
                <div class="box span12">
                    <div class="box-header" data-original-title>
                        <h2><i class="halflings-icon white user"></i><span class="break"></span>All orders</h2>
                        <div class="box-icon">
                            <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                            <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                            <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                        </div>
                    </div>
                    <%@orders=Order.all%>
                    <%= render 'orders/orders'%>
                </div><!--/span-->
            </div><!--/row-->
            </div>
            </div>
                </div>
            </div>
        </div>
</div>

       <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

app/views/admin/review.html.erb
<%=@reviews.each do |review|%>
1
<%end%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin | Airbook</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%=render 'admin/sidebar'%>
	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
        <%= yield %>


</body>
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title))%></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
div.fixed {
    position: fixed;
    bottom: 0;
    right: 0;
    width: 300px;
    border: 3px solid #73AD21;
}
</style>
</head>
<%= render 'shared/header'%>
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<body>

<%= yield %>

</body>
<%= render 'shared/footer'%>
</html>

app/views/order_notifier/received.html.erb
Dear <%= @order.name %>
Thank you for your recent order from AIRBOOK.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from AIRBOOK.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>AIRBOOK Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-7">
					
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<ul class="nav nav-pills nav-stacked">
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<ul class="nav nav-pills nav-stacked">
<!-- 								<li><a href="#">VĂN HỌC</a></li>
								<li><a href="#">KINH TẾ</a></li>
								<li><a href="#">TEEN</a></li>
								<li><a href="#">THIẾU NHI</a></li>
								<li><a href="#">SÁCH HỌC NGOẠI NGỮ - TỪ ĐIỂN</a></li>
							</ul> -->
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<ul class="nav nav-pills nav-stacked">

							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<ul class="nav nav-pills nav-stacked">

							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<%=link_to about_path do%><h2>Về air-book</h2><%end%>
							<form action="#" class="searchform">
								<input type="text" placeholder="Email của bạn" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Hãy nhận thông tin mới từ chúng tôi</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © air-book 2015</p>
				</div>
			</div>
		</div>
</div>

app/views/shared/_header.html.erb
<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<%= link_to root_path do%>
								<h2><%=logo(current_user)%></h2>
							<% end %>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<%if logged_in?	%>
								<li><%= link_to user_path(current_user) do%><i class="fa fa-user"></i> Tài khoản <%end%></li>
								<!-- <li><%= link_to wishlist_path do%><i class="fa fa-star"></i> Sản phẩm yêu thích <%end%></li> -->
								<li><%= link_to cart_path(session[:cart_id]) do%><i class="fa fa-shopping-cart"></i> Giỏ hàng <%end%></li>
								<li><%= link_to logout_path, method: :delete do%><i class="fa fa-fw fa-power-off"></i> Đăng xuat <%end%></li>
								<%else%>
								<li><%= link_to login_path do%><i class="fa fa-lock"></i> Đăng nhập <%end%></li>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><%=link_to root_path do %>Trang chủ<% end %></li>
								<li class="dropdown"><a href="#">Cửa hàng<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><%= link_to shop_path do%>Sản phẩm<% end%></li>
										<li><%= link_to cart_path(session[:cart_id]) do%>Giỏ hàng<%end%></li> 
										<%unless logged_in?%>
										<li><%= link_to login_path do%>Đăng nhập <%end%></li>  
										<%end%>
                                    </ul>
                                </li> 
                    		

								<span class='hotline'><button type="button" class="btn btn-lg btn-danger"><strong>HOTLINE: 1900 1234</strong></button></span>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<%= form_tag(shop_path, :method => "get", id: "search-form") do %>
							<%= text_field_tag :search, params[:search], placeholder: "Search books" %>
							<%= submit_tag "Search" %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

app/views/shared/_recommended_items.html.erb
 <div class="recommended_items"><!--recommended_items-->
            <h2 class="title text-center">Sách Gợi ý </h2>
            
            <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="item active"> 
                  <%Book.where(rec: true).each do |book|%>
                  <div class="col-sm-4">
                    <div class="product-image-wrapper">
                      <div class="single-products">
                        <div class="productinfo text-center">
                          <%=image_tag book.image_file_name, :class =>"image-size"%>
                          <h2><%=book.price%></h2>
                          <%=link_to book_path(book) do%>
                          <p><%=book.title%></p>
                          <%end%>
                          <button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <%end%>
                </div>
              </div>
            </div>
          </div><!--/recommended_items-->