config/routes.rb
Rails.application.routes.draw do
  get 'wishlists/new'

  get 'wishlists/show'

  get 'admin/index'

  get 'orders/new'

  get 'sessions/new'

  get 'user/edit'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'index' =>'home#index'
  get 'admin' => 'admin#index'
  get 'about' => 'home#about'
  get 'users' => 'admin#user'
  get 'shop' => 'books#index'
  get 'bookss' => 'admin#book'
  get 'reviews' => 'admin#review'
  get 'wishlist' => 'wishlists#show'
  root 'home#index'
  get 'orders' => 'admin#order'
  resources :genres
  resources :orders
  resources :wishlists
  resources :users
  resources :carts
  resources :line_items
  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
has_many :reviews, dependent: :destroy
has_many :line_items
has_many :orders, through: :line_items
belongs_to :gerne


before_destroy :in_any_cart

def self.search(search)
  where("title LIKE ?", "%#{search}%") 
  where("abstract LIKE ?", "%#{search}%")
end

private 
def in_any_cart
	if line_items.empty?
		true
	else
		errors.add(:base, "Line_Items presence")
		false
	end
end

	

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	
	def add_book (book_id)
		current_item = line_items.find_by(book_id: book_id)
		if current_item 
			current_item.quantity +=1
		else
			current_item = line_items.build(book_id: book_id)
		end
		current_item
	end
	def total_price
		sum=0
		line_items.each do |item|
		sum = sum + item.total
		end
		sum
	end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  belongs_to :cart
  def total
  	book.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Paypal", "Credit card", "Purchase order" ]
	has_many :line_items, dependent: :destroy
	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
		item.cart_id = nil
		line_items << item
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :wishlist
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :books
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  	include CurrentCart
	before_action :set_cart
  def index
  end
  def about
  	render :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:index, :edit, :update]  
before_action :admin_user,     only: [:destroy]

  def show
    @user=User.find(params[:id])
     if current_user.admin?
        render :layout =>"admin"
      else
        render :layout => "application"
      end
  end
  
  def index 
    @users = User.all
  end
  
  def new
  	@user = User.new
  end
  
    def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		redirect_to root_path
      flash[:success] = "Welcome to Airbook"
  	else
  		render 'new'
  	end
  end
  
  def edit
      @user = User.find(params[:id])
      if current_user.admin?
        render :layout =>"admin"
      else
        render :layout => "application"
      end
  end
  
   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    flash[:success] = "Profile updated"
    redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now[:success] = "User deleted"
    redirect_to users_url
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password,
  				 :password_confirmation)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
  def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    def not_logged_in
      redirect_to(root_url) if (current_user == nil)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(title)
		base_title = "Airbook"
		if title.empty?
			base_title
		else
			title + " | " + base_title
		end
		
	end

	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
	def logo(current_user)
		if current_user.nil?
			"AIRBOOK"
		else
			current_user.name+ "'s" + " AIRBOOK"
		end
		
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id]= user.id
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def logged_in?
		!current_user.nil?		
	end
	def log_out
		session.delete(:user_id)
    	@current_user = nil
	end
	def current_user?(user)
    user == current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%if current_user.admin?%>
<div id="wrapper">
    <div id="page-content-wrapper">
<div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Người dùng <small>Quản lý người dùng</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Trang chủ / <i class="fa fa-users"></i> Người dùng / <%=@user.name%>
                            </li>
                        </ol>
                    </div>
                </div>
<%end%>
<section id="cart_items">
    <div class="container">
      <%unless  current_user.admin?%>
      <div class="breadcrumbs">
              <ol class="breadcrumb">
                <%= link_to "Home", root_path%> >> Sửa thông tin
              </ol>
            </div>
            <%end%>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Lưu lại", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </section>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <%= user.email %>
      <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<center><h1>Sign up</h1></center>
<%=render 'shared/error_messages'%>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.text_field :name, :placeholder =>"Name"%>
      <%= f.email_field :email, :placeholder => "Email"%>
      <%= f.password_field :password, :placeholder =>"Password" %>
      <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User account") %>
<%if current_user.admin?%>
<div id="wrapper">
    <div id="page-content-wrapper">
<div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Người dùng <small>Quản lý người dùng</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Trang chủ / <i class="fa fa-users"></i> Người dùng / <%=@user.name%>'	
                            </li>
                        </ol>
                    </div>
                </div>
<%end%>
<section id="cart_items">
    <div class="container">
      <%unless  current_user.admin?%>
      <div class="breadcrumbs">
              <ol class="breadcrumb">
                <%= link_to "Home", root_path%> >> Tài khoản
              </ol>
            </div>
            <%end%>
             <div class="col-lg-5">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-user fa-fw"></i> Thông tin</h3>
                            </div>
                            <div class="panel-body">
                                <div class="list-group">
                                    <a href="#" class="list-group-item">
                                        <span class="badge"><%=@user.name%></span>
                                        <i class="fa fa-fw fa-user"></i> Tên
                                    </a>
                                    <a href="#" class="list-group-item">
                                        <span class="badge"><%=@user.email%></span>
                                        <i class="fa fa-fw fa-envelope"></i> Email
                                    </a>
                                    <a href="#" class="list-group-item">
                                        <span class="badge"><%=Order.where(name: @user.name).count%></span>
                                        <i class="fa fa-fw fa-check"></i> Số lượng đơn hàng
                                    </a>
                                </div>
                                <%=link_to edit_user_path do%>
                                 <div class="text-right">
                                    <span> Sửa thông tin <i class="fa fa-arrow-circle-right"></i></span>
                                </div>
                                <%end%>
                            </div>
                        </div>
                    </div>

                     <div class="col-lg-5">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Lịch sử đơn hàng</h3>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Ngày đặt hàng</th>
                                                <th>Thời gian đặt hàng</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        	<%@orders=Order.where(name: @user.name)%>
                                            <%@orders.each do |order|%>
                                            <tr>
                                                <td><%=order.id%></td>
                                                <td><%=order.created_at.strftime("%d/%m/%Y")%></td>
                                                <td><%=order.created_at.strftime("%H:%M")%></td>
                                                <td> <%= link_to order_path(order) do%>
                                      <span class="btn btn-success">
                                       <i class="fa fa-info"></i></i>
                                    </span>
                                    <% end %> 
                                 <%= link_to order, method: :delete, data: { confirm: 'Are you sure?' } do%>
                                      <span class="btn btn-danger">
                                       <i class="fa fa-trash"></i>
                                    </span>
                                    <% end %></td>

                                            </tr>
                                            <% end %>
                                        </tbody>
                                    </table>
                                </div>
                            
                            </div>
                        <%if current_user.admin?%>
                             </div>
                    </div>
                        <%end%>
                       
      <!-- <div class="row">
        <div class="col-md-5">
        	<ul class="list-group">
                            <li class="list-group-item"><i class="fa fa-user"></i> <span class='pull-right'><%=@user.name%></span></li>
                            <li class="list-group-item"><i class="fa fa-envelope"></i> <span class='pull-right'><%=@user.email%></span></li>
                            <li class="list-group-item"><i class="fa fa-credit-card"></i> <span class='pull-right'><%=Order.where(name: @user.name).count%></span></li>
                        </ul>
                        <%=link_to "Show orders"%>

        </div>
      </div> -->
    </div>
  </section>