config/routes.rb
Rails.application.routes.draw do
  get 'wishlists/new'

  get 'wishlists/show'

  get 'admin/index'

  get 'orders/new'

  get 'sessions/new'

  get 'user/edit'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'index' =>'home#index'
  get 'admin' => 'admin#index'
  get 'about' => 'home#about'
  get 'users' => 'admin#user'
  get 'shop' => 'books#index'
  get 'bookss' => 'admin#book'
  get 'reviews' => 'admin#review'
  get 'wishlist' => 'wishlists#show'
  root 'home#index'
  get 'orders' => 'admin#order'
  resources :genres
  resources :orders
  resources :wishlists
  resources :users
  resources :carts
  resources :line_items
  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
has_many :reviews, dependent: :destroy
has_many :line_items
has_many :orders, through: :line_items
belongs_to :gerne


before_destroy :in_any_cart

def self.search(search)
  where("title LIKE ?", "%#{search}%") 
  where("abstract LIKE ?", "%#{search}%")
end

private 
def in_any_cart
	if line_items.empty?
		true
	else
		errors.add(:base, "Line_Items presence")
		false
	end
end

	

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	
	def add_book (book_id)
		current_item = line_items.find_by(book_id: book_id)
		if current_item 
			current_item.quantity +=1
		else
			current_item = line_items.build(book_id: book_id)
		end
		current_item
	end
	def total_price
		sum=0
		line_items.each do |item|
		sum = sum + item.total
		end
		sum
	end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  belongs_to :cart
  def total
  	book.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	PAYMENT_TYPES = [ "Paypal", "Credit card", "Purchase order" ]
	has_many :line_items, dependent: :destroy
	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
		item.cart_id = nil
		line_items << item
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :wishlist
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :books
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  	before_action :set_cart, only: [:show, :edit, :update, :destroy]
  	before_action :logged_in_user, only: [:create]
  	
	def show
		@cart =Cart.find(params[:id])
	end
	def destroy
		@cart.destroy if @cart.id == session[:cart_id]
		session[:cart_id] = nil
		respond_to do |format|
		format.html { redirect_to shop_url }
		format.json { head :no_content }
	end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  	include CurrentCart
	before_action :set_cart
  def index
  end
  def about
  	render :layout => false
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(title)
		base_title = "Airbook"
		if title.empty?
			base_title
		else
			title + " | " + base_title
		end
		
	end

	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
	def logo(current_user)
		if current_user.nil?
			"AIRBOOK"
		else
			current_user.name+ "'s" + " AIRBOOK"
		end
		
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id]= user.id
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def logged_in?
		!current_user.nil?		
	end
	def log_out
		session.delete(:user_id)
    	@current_user = nil
	end
	def current_user?(user)
    user == current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/carts/_cart.html.erb
<h2>Your Cart (<%= @cart.line_items.count%>)</h2>
<table>
<%= render 'line_items/line_item_sidebar' %>
<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell"><%=(cart.total_price) %></td>
</tr>
</table>
<%= button_to 'Checkout', new_order_path, method: :get%>
<%= button_to 'Empty cart', cart, method: :delete,
data: { confirm: 'Are you sure?' } %>

app/views/carts/show.html.erb
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
					<%= link_to "Home", root_path%> >> Shopping Cart
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<% @cart.line_items.each do |item|%>
							<tr>
								<% if item == @current_item %>
									<tr id="current_item">
								<% else %>
									<tr>
								<% end %>
								<td>
									<%= link_to book_path(item.book_id) do %>
									<%=image_tag item.book.image_file_name, :class =>"image-small"%>
									<% end %>
								</td>
								<td class="cart_description">
									<%= link_to book_path(item.book_id) do %>
									<h4><%=item.book.title%></h4>
									<p>by <%=item.book.author%></p>
									<% end %>
								</td>
								<td>
									<p><%=item.book.price%></p>
								</td>
								<td>
									<p><%=item.quantity%></p>
								</td>
								<td class="cart_total">
									<p class="cart_total_price"><%= item.total%></p>
								</td>
								<!-- <td class="cart_delete">
									<%= link_to "Delete", item, method: :delete%>
									<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
								</td> -->
							</tr>
						<%end%>
					</tbody>
				</table>
				<div class="col-sm-6 pull-right">
					<div class="total_area">
						<ul>
							<li>Total <span><%=@cart.total_price%></span></li>
						</ul>
						<%= button_to "Checkout", new_order_path, method: :get %>
							<%= button_to 'Empty cart', @cart, method: :delete,
														data: { confirm: 'Are you sure?' } %>
							<!-- <a class="btn btn-default check_out" href="">Check Out</a> -->
					</div>
				</div>
			</div>
		</div>
	</section> <!--/#cart_items-->